In [1]:
import numpy as np

print("="*50)
print("STUDENT MARKS ANALYSER")
print("="*50)

dataset = np.random.randint(25,101,size=(20,3))
print(dataset)

print("Average marks per student :",np.round(dataset.mean(axis=1),2))
print("Average marks per subject :",np.round(dataset.mean(axis=0),2))
print("highest score : ",dataset.max())
print("lowest score : ",dataset.min())
passed = dataset[np.any(dataset>=40,axis=1)]
print("passed :",passed)
top_student = dataset[np.any(dataset>80,axis=1)]
print("top students are :",top_student)



STUDENT MARKS ANALYSER
[[ 53  79  52]
 [ 64  27  41]
 [ 97  77  96]
 [ 25  41  57]
 [ 44  38  29]
 [ 98  73  46]
 [ 64  52  28]
 [ 29  58  98]
 [ 53  44  30]
 [ 50  96  40]
 [ 61  78  96]
 [ 32  39  88]
 [ 70 100  54]
 [ 53  46  67]
 [ 62  40  43]
 [ 53  57  26]
 [ 53  99  39]
 [ 92  85  72]
 [ 81  48  77]
 [ 67  31  36]]
Average marks per student : [61.33 44.   90.   41.   37.   72.33 48.   61.67 42.33 62.   78.33 53.
 74.67 55.33 48.33 45.33 63.67 83.   68.67 44.67]
Average marks per subject : [60.05 60.4  55.75]
highest score :  100
lowest score :  25
passed : [[ 53  79  52]
 [ 64  27  41]
 [ 97  77  96]
 [ 25  41  57]
 [ 44  38  29]
 [ 98  73  46]
 [ 64  52  28]
 [ 29  58  98]
 [ 53  44  30]
 [ 50  96  40]
 [ 61  78  96]
 [ 32  39  88]
 [ 70 100  54]
 [ 53  46  67]
 [ 62  40  43]
 [ 53  57  26]
 [ 53  99  39]
 [ 92  85  72]
 [ 81  48  77]
 [ 67  31  36]]
top students are : [[ 97  77  96]
 [ 98  73  46]
 [ 29  58  98]
 [ 50  96  40]
 [ 61  78  96]
 [ 32  39  88]
 [ 70 100  54]
 [ 53